service: my-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins :
  - serverless-offline

functions:
  hello:
    handler: ./handler.hello
  getUser:
    handler: src/handlers/getUser.getUser
    events:
    - httpApi:
        path: /
        method: get
  postUser:
    handler: src/handlers/postUser.postUser
    events:
    - httpApi:
        path: /
        method: post
  deleteUser:
    handler: src/handlers/deleteUser.deleteUser
    events:
    - httpApi:
        path: /
        method: delete
  putUser:
    handler: src/handlers/putUser.putUser
    events:
    - httpApi:
        path: /
        method: put
        RequestParameters:
          - method.request.querystring.email:
            Required: true