service: serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins :
  - serverless-offline

functions:
  hello:
    handler: ./handler.hello
  getUser:
    handler: src/handlers/getUser.getUser
    events:
    - httpApi:
        path: /
        method: get
  postUser:
    handler: src/handlers/postUser.postUser
    events:
    - httpApi:
        path: /
        method: post